version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: .
    expose:
        - 5555
    volumes:
        - . :/usr/src/app

  reactapp:
    container_name: reactapp
    build: ./client
    expose:
        - 3333
    volumes:
        - ./client:/usr/src/app
  nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - expressapp
        - reactapp
    restart: always