version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: .
    expose:
        - 5000
    volumes:
        - .:/usr/src/app

  reactapp:
    container_name: reactapp
    build: ./client
    expose:
        - 3000
    volumes:
        - ./client:/usr/src/app
  nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - expressapp
        - reactapp
    restart: always


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: passgamma
      MYSQL_DATABASE: gamma
      MYSQL_USER: gammauser
      MYSQL_PASSWORD: passgamma
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080